---

- name: Download agent
  get_url: url=https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py dest=/tmp

- name: Get AWS region
  command: curl http://169.254.169.254/latest/meta-data/placement/availability-zone
  register: aws_region_role_aws_tools
  when: aws_env

- name: Create directory for config
  file: path={{ item }} state=directory
  with_items:
    - /var/awslogs/etc

- name: Create aws logs agent config
  template: src=templates/aws-logs-agent.conf.j2 dest=/tmp/awslogs.conf

- name: Execute installer in aws env
  command: python /tmp/awslogs-agent-setup.py --non-interactive -c /tmp/awslogs.conf --region={{ aws_region_role_aws_tools.stdout[:-1] }}
  when: aws_env

- name: Execute installer in test env
  command: python /tmp/awslogs-agent-setup.py --non-interactive -c /tmp/awslogs.conf --region=eu-west-1
  when: not aws_env
