---

- name: Install from apt when debian based
  apt: name={{ item }} state=latest
  with_items:
    - unzip
    - libwww-perl
    - libdatetime-perl
  when: ansible_os_family == "Debian"

- name: Download script
  get_url: url=http://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.1.zip dest=/tmp

- name: Unarchive script archive
  unarchive: src=/tmp/CloudWatchMonitoringScripts-1.2.1.zip dest=/usr/bin copy=no

- name: Install script on crontab
  cron: name="Send metrics" minute="*/5" job="/usr/bin/aws-scripts-mon/mon-put-instance-data.pl --mem-util --disk-space-util --disk-path=/ --from-cron"
