---

- name: Install from apt when debian based
  apt: name={{ item }} state=latest
  with_items:
    - unzip
    - libwww-perl
    - libdatetime-perl
  when: ansible_os_family == "Debian"

- name: Install from yum when Red Hat based
  yum: name={{ item }} state=latest
  with_items:
    - zip
    - unzip
    - perl-Switch
    - perl-DateTime
    - perl-Sys-Syslog
    - perl-LWP-Protocol-https
    - perl-Digest-SHA
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install from yum when Amazon Linux
  yum: name={{ item }} state=latest
  with_items:
    - perl-Switch
    - perl-DateTime
    - perl-Sys-Syslog
    - perl-LWP-Protocol-https
  when: ansible_distribution == 'Amazon'

- name: Download script
  get_url: url=http://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.1.zip dest=/tmp

- name: Unarchive script archive
  unarchive: src=/tmp/CloudWatchMonitoringScripts-1.2.1.zip dest=/usr/bin copy=no

#Report memory and disk space utilization to CloudWatch every 1 minutes
- name: Install script on crontab
  cron: name="Send metrics" minute="*/1" job="/usr/bin/aws-scripts-mon/mon-put-instance-data.pl --mem-util --disk-space-util --disk-path=/ --from-cron"
