---

- name: Install from apt when Debian based
  apt: name=awscli state=latest
  when: ansible_os_family == "Debian"

- name: Install from yum when Red Hat based
  pip: name=awscli
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'